// ============================================================
// Balance Config — Optimal parameters found by simulated annealing
//
// Generated by: npx tsx tools/optimize/optimize.ts
// Optimized for: 10K particles / 50 entities
// ============================================================

import type { SearchParams } from "./TunableParams.js";

/** SA-optimized balance config (10K/50) — last working 1-action values */
export const BALANCE: SearchParams = {
  drainBase: 1.2756,
  drainScale: 1.0,
  absorbScale: 1.87,
  qiCostPerRealm: 13.431,
  breakthroughSuccessRate: 0.31,
  breakthroughThreshold: 0.7,
  spawnBaseChance: 0.08,
};
