// ============================================================
// Balance Config — Optimal parameters found by simulated annealing
//
// Generated by: npx tsx tools/optimize/optimize.ts
// Fitness: 0.290 (actionDiversity=0.321, speciesDiversity=0.368, survival=0.203)
// ============================================================

import type { SearchParams } from "./TunableParams.js";

/** SA-optimized balance config — spawnBaseChance manually raised to preserve species diversity */
export const BALANCE: SearchParams = {
  drainBase: 1.3012,
  drainScale: 1.3762,
  absorbScale: 1.87,
  qiCostPerRealm: 12.369,
  successExponent: 3,
  spawnBaseChance: 0.015, // SA found 0.006 but too low for species diversity
};
