// ============================================================
// Balance Config — Optimal parameters found by simulated annealing
//
// Generated by: npx vitest run balance.spec.ts
// Score: 0.902 (survival=1.0, diversity=0.74, breakthrough=1.0, ecosystem=1.0)
//
// To re-optimize, run: npx vitest run src/__tests__/balance.spec.ts
// Then update this file with the best params printed.
// ============================================================

import type { SearchParams } from "./TunableParams.js";

/** SA-optimized balance config (score 0.902) */
export const BALANCE: SearchParams = {
  drainRatio: 0.019,
  absorbRatio: 0.271,
  breakthroughCostRatio: 0.386,
  breakthroughSuccessRate: 0.201,
  combatDecisiveness: 0.3479633346927508,
  ecologyResilience: 0.8252277027150005,
  breakthroughThreshold: 0.8,
  drainBase: 1.2,
  infiltrationK: 2.88,
  dissipationK: 3.34,
};
